#!/usr/bin/env python
from textblob import TextBlob
x=open('filesa.txt','r+')
tex=x.readline()
x=TextBlob(tex)
wlist=x.tags
i=0
for word in wlist:
 i=i+1
print i
j=0
for sent in x.sentences:
 j+=1
print j
print(x.sentences)
print(x.words)
wsort=sorted(wlist)
print wsort
